### ISSUE TITLE
category 구분 벡터 스토어 저장

### ISSUE THREAD

**Issue by minmaru99** [pladata-encore/DA36-mini4-app2#18]
## 🌈 Success criteria

1. 상세설명
2.

## 👷 To-do

- [x] 할일 1 저장된 자료를 사전에 카테고리별로 분류
- [x] 할일 2 카테고리별 벡터 스토어 저장 
- [x] 할일 2 텍스트 임베딩 모델 비교 - 3-small, ada
